spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.ezlearning: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persistAuthorization: true
    tryItOutEnabled: true
